# Generated by Django 2.2.6 on 2019-12-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
