# Generated by Django 2.2.6 on 2019-12-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_productdetails_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='Tagline',
            field=models.CharField(default='miii', max_length=25),
        ),
    ]
