# Generated by Django 2.2.6 on 2020-02-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_productdetails_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
