# Generated by Django 2.2.6 on 2019-12-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Cart_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
