# Generated by Django 2.2.6 on 2019-12-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0007_auto_20191217_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Categary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=25)),
                ('service_Description', models.TextField()),
                ('service_Name', models.CharField(max_length=25)),
            ],
        ),
    ]
