# Generated by Django 2.2.6 on 2019-12-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0009_service_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_list',
            new_name='servant',
        ),
    ]
