# Generated by Django 2.2.6 on 2019-12-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0010_auto_20191223_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servant',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=25),
        ),
    ]
