# Generated by Django 2.2.6 on 2020-02-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0011_auto_20191223_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servant',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Services', to='seller.Category'),
        ),
        migrations.DeleteModel(
            name='Service_Categary',
        ),
    ]
