# Generated by Django 2.2.6 on 2020-02-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0013_auto_20200208_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='area',
            new_name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
