# Generated by Django 2.2.6 on 2020-02-08 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0015_auto_20200208_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServantBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone_no', models.BigIntegerField()),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Cancel', 'Cancel')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ser.servant')),
            ],
        ),
    ]
