# Generated by Django 2.2.6 on 2020-02-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0017_orderitem_productorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=25)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Phone_number', models.BigIntegerField(default=0)),
                ('Address', models.TextField()),
                ('City', models.TextField()),
                ('Gender', models.CharField(max_length=25)),
                ('Image', models.ImageField(null=True, upload_to='User Image')),
            ],
        ),
    ]
