# Generated by Django 2.2.6 on 2020-02-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0018_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='Gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=25),
        ),
    ]
