# Generated by Django 2.2.6 on 2020-02-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0019_auto_20200214_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='City',
            field=models.CharField(max_length=25),
        ),
    ]
